object CardTypeEnum extends Enumeration {
	val TWO = CardFaceValue(2,"2")
	val THREE = CardFaceValue(3,"3")
	val FOUR = CardFaceValue(4,"4")
	val FIVE = CardFaceValue(5,"5")
	val SIX = CardFaceValue(6,"6")
	val SEVEN = CardFaceValue(7,"7")
	val EIGHT = CardFaceValue(8,"8")
	val NINE = CardFaceValue(9,"9")
	val TEN = CardFaceValue(10,"10")
	val JACK = CardFaceValue(10,"J")
	val QUEEN = CardFaceValue(10,"Q")
	val KING = CardFaceValue(10,"K")
	val ACE = CardFaceValue(11,"A",1)
}
